# Generated by Django 3.2.10 on 2022-09-14 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name="titre de l'archive")),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='description')),
                ('confidence', models.CharField(choices=[('p', 'moi uniquement'), ('d', 'les membres du department'), ('t', 'tout le système')], default='p', max_length=2, verbose_name='Qui peut voir cet archive')),
                ('Date_creation', models.DateField(auto_now=True, verbose_name='date de création')),
                ('Date_peremtion', models.DateField(blank=True, null=True, verbose_name='date de péremption')),
                ('Date_modification', models.DateField(blank=True, default='2022-09-14', null=True, verbose_name='date de la dernière modification')),
                ('nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='nom du fichier')),
                ('type', models.CharField(blank=True, choices=[('pdf', 'fichier pdf'), ('word', 'fichier word'), ('excel', 'fichier excel'), ('video', 'fichier video'), ('image', 'fichier image'), ('texte', 'fichier texte')], default='pdf', max_length=50, null=True, verbose_name='type du fichier')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='archive/fichiers/', verbose_name='fichier annexe')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.agent')),
            ],
            options={
                'ordering': ['Date_creation', 'Date_modification'],
            },
        ),
    ]
