# Generated by Django 3.2.10 on 2022-09-14 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(choices=[('direction', 'direction'), ('secretariat', 'secretariat'), ('marketing', 'marketing'), ('gestion comptable', 'gestion comptable'), ('vendeur', 'vendeur')], max_length=100)),
                ('poste', models.CharField(default='aucun', max_length=100, verbose_name='poste occupé')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='utilisateur/profile/', verbose_name='photo de profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
